name: Check Links

on:
  schedule:
    - cron: '0 0 * * 0'  # Cada domingo a medianoche
  pull_request:
    branches: [ main ]

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress '**/*.md' '**/*.html'
          fail: true
